name: teamcoder_ebm
channels:
  - conda-forge
dependencies:
  - python=3.9 
  - pip
  - xlrd
  - pandas
  - matplotlib
  - nilearn
  - tqdm
  - ipython
  - ipympl
  - jupyterlab
  - numpy
  - pip:
    - git+https://github.com/noxtoby/awkde
    - git+https://github.com/ucl-pond/kde_ebm


