name: teamcoder_ebm
channels:
  - conda-forge
dependencies:
  - python=3.7 
  - pip
  - pandas
  - nibabel
  - nilearn
  - jupyterlab
  - numpy=1.16.3
  - fsleyes
  - pip:
    - antspyx
    - niwidgets


