name: teamcoder_ebm
channels:
  - conda-forge
dependencies:
  - python=3.7 
  - pip
  - pandas
  - nibabel
  - nilearn
  - tqdm
  - jupyterlab
  - rise
  - jupyter_nbextensions_configurator
  - numpy=1.16.3
  - fsleyes
  - pip:
    - antspyx
    - niwidgets
    - git+https://github.com/noxtoby/awkde
    - git+https://github.com/ucl-pond/kde_ebm


