name: teamcoder_ebm_facilitator
channels:
  - conda-forge
dependencies:
  - python=3.7 
  - pip
  - xlrd
  - pandas
  - matplotlib
  - nibabel
  - nilearn
  - tqdm
  - jupyterlab
  - rise
  - numpy=1.16.3
  - pip:
    - antspyx
    - niwidgets
    - git+https://github.com/noxtoby/awkde
    - git+https://github.com/ucl-pond/kde_ebm