name: teamcoder_ebm
channels:
  - conda-forge
dependencies:
  - python=3.7 
  - pip
  - xlrd
  - pandas
  - nilearn
  - tqdm
  - jupyterlab
  - numpy
  - pip:
    - git+https://github.com/noxtoby/awkde
    - git+https://github.com/ucl-pond/kde_ebm


